core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("about/",views.AboutView.as_view(), name="about"),
    path("contact/",views.ContactView.as_view(), name="contact"),
]

ecart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

core/models.py
from django.db import models


class UnitModel(models.Model):
    name = models.CharField(max_length=128)
    base = models.ForeignKey("self", on_delete=models.CASCADE, blank=True, null=True)
    symbol = models.CharField(max_length=3)
    conversion_rate = models.FloatField(default=1.0)

    def __str__(self):
        return self.name


class CategoryModel(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField()
    parent = models.ForeignKey("self", on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name


class ProductModel(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(max_length=500)
    price = models.FloatField()
    image = models.ImageField(upload_to="product/image/", default="default/product.jpg")
    unit = models.ForeignKey(
        UnitModel, on_delete=models.SET_NULL, null=True, blank=True
    )
    category = models.ForeignKey(
        CategoryModel, on_delete=models.SET_NULL, null=True, blank=True
    )
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name

core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic as views

class HomeView(views.TemplateView):
    template_name = "core/home.html"

class AboutView(views.TemplateView):
    template_name = "core/about.html"

class ContactView(views.TemplateView):
    template_name = "core/contact.html"
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=\, initial-scale=1.0">
    <title>Ecart</title>
    {% include "includes/style.html" %}
</head>
<body>
    {% include "includes/message.html" %}
    {% include "includes/navbar.html" %}
    {% block content %}{% endblock %}
    {% include "includes/footer.html" %}

    {% include "includes/script.html" %}
</body>
</html>

templates/core/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About Page</h1>

{% endblock %}  

templates/core/contact.html
{% extends 'base.html' %}
{% block content %}

<h1>Contact Page</h1>

{% endblock %}  

templates/core/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Hello World</h1>
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="25e6437798b5856bad8e37b4c2254cb3c3d533d9.jpeg" class="d-block w-100" alt="pic1">
      </div>
      <div class="carousel-item">
        <img src="88722b809f818082cdf1c2fc90757258b5f04d66.jpeg" class="d-block w-100" alt="pic2">
      </div>
      <div class="carousel-item">
        <img src="photo-1514125669375-59ee3985d08b.jpg" class="d-block w-100" alt="pic3">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
{% endblock %}  

templates/includes/footer.html
<footer>
    All Rights Are Reserved &copy; 2023
</footer>

templates/includes/navbar.html
<!-- <div class="container" style="height: 50px; width: 100%; background-color:blanchedalmond;">
    <nav>
        <a href="{% url 'core:home' %}">home</a>
        <a href="{% url 'core:about' %}">about</a>
    </nav>   
</div> -->
<nav class="navbar navbar-expand-lg navbar-light red-100">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Ecart</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Home</a>
          <a class="nav-link" href="{% url 'core:about' %}">About</a>
          <a class="nav-link" href="{% url 'core:contact' %}">Contact</a>
          
        </div>
      </div>
    </div>
  </nav>

templates/includes/script.html
{% load static %}
    <script src="{% static 'bootstrap-5.0.2-dist/bootstrap-5.0.2-dist/js/bootstrap.js' %}"></script>
    <script src="{% static 'fontawesome-free-6.2.1-web/js/all.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>

templates/includes/style.html
{% load static%}
    <link rel="stylesheet" href="{% static 'bootstrap-5.0.2-dist/bootstrap-5.0.2-dist/css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'fontawesome-free-6.2.1-web/css/all.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" href="/static/css/style.css"/>